export default ASYNCSTORAGE_USER_DATA =
{
    FIRST_NAME          : "USER_FIRST_NAME",
    LAST_NAME           : "USER_LAST_NAME",
    PROFILE_PHOTO       : "USER_PROFILE_PHOTO",

    FIREBASE_TOKEN      : "FIREBASE_TOKEN",
    FIREBASE_USER_ID    : "FIREBASE_USER_ID",
    FIREBASE_TOKEN_DATE : "FIREBASE_TOKEN_DATE",
}
